/**
 * Reads the v2 DEMO instance BACK FROM THE CHAIN and writes docs/SEEDS.md.
 * The seed script's own log (docs/seed-v2.json) is used only for transaction
 * hashes; every outcome, status, enum and balance below is read from views.
 *
 *   node collect_v2.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { connect } from "./harness.mjs";

const dep = JSON.parse(readFileSync(new URL("../deployments.json", import.meta.url))).deployments.studiodev;
const address = dep.AppAuditV2Demo.address;
const consumer = dep.AppTrustConsumerV2.address;
const seed = JSON.parse(readFileSync(new URL("../docs/seed-v2.json", import.meta.url), "utf8"));
const C = connect({ address, role: "trigger" });
const K = connect({ address: consumer, role: "trigger" });
const plain = (v) => JSON.parse(JSON.stringify(v, (k, x) => (typeof x === "bigint" ? x.toString() : x instanceof Map ? Object.fromEntries(x) : x)));
const view = async (m, a = []) => plain(await C.view(m, a));
const EX = "https://explorer-studio-dev.genlayer.com";
const tx = (h) => (h ? `[${h.slice(0, 10)}…](${EX}/tx/${h})` : "—");
const gen = (w) => (Number(BigInt(w ?? 0) * 10000n / 10n ** 18n) / 10000).toString();

const EXPECT = {
  "cross-snapchat-identifiers": ["Snapchat", "Identifiers · shared", "CONTRADICTED", "Play: “No data shared with third parties”; App Store tracks Identifiers"],
  "cross-capcut-identifiers": ["CapCut", "Identifiers · shared", "CONTRADICTED", "Play: “No data shared”; App Store tracks Identifiers"],
  "cross-whatsapp-location": ["WhatsApp", "Location · shared", "INCONCLUSIVE", "Play: “No data shared”; App Store has no tracking section (silent)"],
  "policy-linkedin-identifiers#1": ["LinkedIn", "Identifiers · shared", "CONTRADICTED", "policy: shares “hashed IDs or device identifiers” with advertisers; Play: “No data shared”"],
  "policy-linkedin-identifiers#2": ["LinkedIn", "Identifiers · shared", "CONTRADICTED", "run 2"],
  "policy-capcut-personal#1": ["CapCut", "Personal info · shared", "CONTRADICTED", "policy: “we do ‘share’ your information … for … advertisements”; Play: “No data shared”"],
  "policy-capcut-personal#2": ["CapCut", "Personal info · shared", "CONTRADICTED", "run 2"],
  "policy-pinterest-identifiers#1": ["Pinterest", "Identifiers · shared", "CLAIM_VERIFIED", "policy discloses cookie IDs / hashed email to ad platforms; Play declares Device IDs shared"],
  "policy-pinterest-identifiers#2": ["Pinterest", "Identifiers · shared", "CLAIM_VERIFIED", "run 2 (defaulted, see below)"],
  "policy-pinterest-identifiers#3": ["Pinterest", "Identifiers · shared", "CLAIM_VERIFIED", "run 2, re-filed after #2 defaulted"],
  "label-whatsapp-location#1": ["WhatsApp", "“does not collect location data”", "CONTRADICTED", "v1 claim kind; Play declares Approximate location"],
  "label-whatsapp-location#2": ["WhatsApp", "“does not collect location data”", "CONTRADICTED", "run 2"],
};

const txOf = (label, method) => seed.txs.filter((t) => t.label.startsWith(label) && t.method === method && t.status !== "UNSETTLED");
const lastOk = (label, method) => {
  const rows = txOf(label, method);
  return rows.length ? rows[rows.length - 1].hash : null;
};

const lines = [];
const out = (s = "") => lines.push(s);
out("# SEEDS — AppAudit v2 on Studio Dev");
out();
out(`Demo instance \`${address}\` ([explorer](${EX}/address/${address})), consumer \`${consumer}\`.`);
out(`Driven by \`test/seed_v2.mjs\`; this file is generated by \`test/collect_v2.mjs\` from views read back from the chain on ${new Date().toISOString()}. Real apps only.`);
out();
out("## Cases");
out();
out("| # | key | app | question | expected | filing | capture confirmed | judgment | verdict | settlement adv / dev / protocol GEN | file | confirm | respond | judge | finalize |");
out("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
const cases = {};
let mismatches = [];
for (const [key, id] of Object.entries(seed.cases)) {
  if (!id) continue;
  const c = await view("get_case", [id]);
  cases[key] = c;
  const [app, q, want, why] = EXPECT[key] ?? [c.app_label, c.topic, "", ""];
  const actual = c.outcome || `(${c.status})`;
  if (want && actual !== want) mismatches.push([key, want, actual, why, c]);
  if (want && actual === want && c.kind === "POLICY_LABEL" && c.filing_result !== c.judgment_result) {
    mismatches.push([key, want, actual + " (filing read " + c.filing_result + ")", why, c]);
  }
  const filing = c.kind === "LABEL" ? `case ${c.filing.status}` : `${c.filing.status}${c.kind === "CROSS_STORE" ? " / " + c.filing.status2 : ""} → ${c.filing_result}`;
  const judgment = c.judged_at ? (c.kind === "LABEL" ? `${c.judgment.case} → ${c.judgment_result}` : `${c.judgment.status}${c.kind === "CROSS_STORE" ? " / " + c.judgment.status2 : ""} → ${c.judgment_result}`) : "—";
  const s = c.settlement;
  out(`| ${id} | ${key} | ${app} | ${q} | ${want} | ${filing} | ${c.filing.confirmed ? "yes" : "no"} | ${judgment} | **${actual}** | ${gen(s.owed_advocate_wei)} / ${gen(s.owed_respondent_wei)} / ${gen(s.owed_protocol_wei)} | ${tx(lastOk(key + " file", "file_cross_store") || lastOk(key + " file", "file_policy") || lastOk(key + " file", "file_challenge"))} | ${tx(lastOk(key + " confirm", "confirm_filing"))} | ${tx(lastOk(key + " respond", "respond"))} | ${tx(lastOk(key + " judge", "judge"))} | ${tx(lastOk(key + " finalize", "finalize"))} |`);
}
out();
if (mismatches.length) {
  out("### Where actual ≠ expected");
  out();
  for (const [key, want, actual, , c] of mismatches) {
    if (c.status === "DEFAULTED") {
      out(`- **${key}** (case #${c.challenge_id}): expected ${want}, got DEFAULTED — not a reading. Studio left two of the seed's \`confirm_filing\` re-sends PENDING for 15 minutes each (both cancelled by their sender), which outlasted the demo's 10-minute response window; \`respond\` was then correctly refused and the case defaulted (advocate's stake claimable in full). The seed now responds before confirming. The second judged Pinterest run is the re-filed \`policy-pinterest-identifiers#3\`.`);
      continue;
    }
    out(`- **${key}**: expected ${want}, got ${actual}. Filing: ${c.filing_result || c.filing.status}; judgment: ${c.judgment_result || "—"}${c.kind === "POLICY_LABEL" ? `; policy enum at filing ${c.filing.policy_enum}, at judgment ${c.judgment.policy_enum || c.judgment.policy_state || "—"}` : ""}. Reason on chain: ${c.reason}`);
  }
  out();
} else {
  out("Every verdict matched the expectation written before the run.");
  out();
}

out("## Model agreement (every model-decided seed run twice)");
out();
out("The POLICY_LABEL and LABEL seeds were each filed and judged twice, the second run after the first had closed. Each run is itself a consensus of validators on different model families; the table compares what each run agreed on.");
out();
out("| question | run 1 filing | run 1 judgment | run 2 filing | run 2 judgment | verdicts agree |");
out("|---|---|---|---|---|---|");
let agreeN = 0;
let totalN = 0;
for (const base of ["policy-linkedin-identifiers", "policy-capcut-personal", "policy-pinterest-identifiers", "label-whatsapp-location"]) {
  const a = cases[base + "#1"];
  // Run 2 is the second JUDGED run: a run-2 case that defaulted (Studio jam
  // outlasted its response window) is replaced by its re-filed #3.
  const b = cases[base + "#3"]?.judged_at ? cases[base + "#3"] : cases[base + "#2"];
  if (!a || !b) { out(`| ${base} | ${a ? "run" : "missing"} | | ${b ? "run" : "missing"} | | — |`); continue; }
  const f = (c, when) => c.kind === "POLICY_LABEL"
    ? `${c[when].policy_enum || c[when].policy_state || "—"} → ${when === "filing" ? c.filing_result : c.judgment_result || "—"}`
    : when === "filing" ? `case ${c.filing.status}` : `${c.judgment_result || "—"}`;
  const same = a.outcome && a.outcome === b.outcome;
  totalN++;
  if (same) agreeN++;
  out(`| ${base} | ${f(a, "filing")} | ${f(a, "judgment")} | ${f(b, "filing")} | ${f(b, "judgment")} | ${same ? "yes" : "**no**"} (${a.outcome || a.status} / ${b.outcome || b.status}) |`);
}
out();
out(`**${agreeN} of ${totalN}** model-decided questions reached the same verdict on both runs.`);
out();
// Stricter: every individual model READING (the policy enum at filing and at
// judgment, both runs; the claim verdict at judgment, both runs).
let readings = 0;
let sameAsMajority = 0;
const splits = [];
for (const base of ["policy-linkedin-identifiers", "policy-capcut-personal", "policy-pinterest-identifiers", "label-whatsapp-location"]) {
  const runs = [cases[base + "#1"], cases[base + "#3"]?.judged_at ? cases[base + "#3"] : cases[base + "#2"]].filter(Boolean);
  const vals = [];
  for (const c of runs) {
    if (c.kind === "POLICY_LABEL") {
      if (c.filing.policy_enum) vals.push(c.filing.policy_enum);
      if (c.judgment.policy_enum) vals.push(c.judgment.policy_enum);
    } else if (c.judgment_result) {
      vals.push(c.judgment_result);
    }
  }
  const counts = {};
  for (const v of vals) counts[v] = (counts[v] ?? 0) + 1;
  const top = Math.max(0, ...Object.values(counts));
  readings += vals.length;
  sameAsMajority += top;
  if (top < vals.length) splits.push(`${base}: ${vals.join(" / ")}`);
}
out(`Individual readings: **${sameAsMajority} of ${readings}** agree with their question's majority reading.${splits.length ? " Split: " + splits.join("; ") + "." : ""}`);
out();

const rejectedRows = seed.txs.filter((t) => t.returned?.status === "REJECTED");
const deliberate = rejectedRows.filter((t) => /^(identity:|cross:|withdraw .* again)/.test(t.label));
const incidental = rejectedRows.filter((t) => !deliberate.includes(t));
out("## Refusals, live");
out();
out("Deliberate: each was re-sent until the chain's own refusal counter moved, so every row is an AGREED refusal.");
out();
out("| what | call | result on chain | tx |");
out("|---|---|---|---|");
for (const t of deliberate) out(`| ${t.label} | \`${t.method}\` | ${String(t.returned.reason).replace(/\|/g, "/")} | ${tx(t.hash)} |`);
out();
out("Incidental refusals during the run (the contract refusing a re-send correctly):");
out();
out("| what | call | result on chain | tx |");
out("|---|---|---|---|");
for (const t of incidental) out(`| ${t.label} | \`${t.method}\` | ${String(t.returned.reason).replace(/\|/g, "/")} | ${tx(t.hash)} |`);
out();
const cancelled = seed.txs.filter((t) => t.status === "CANCELED" || /cancelled/.test(t.label));
const stuck = seed.txs.filter((t) => t.status === "UNSETTLED");
const jammed = [...new Map([...stuck, ...cancelled].map((t) => [t.hash, t])).values()];
out(`**Studio queue jams.** ${jammed.length} writes sat PENDING for 15+ minutes and blocked every later write to the contract; each was cancelled by its own sender (\`sim_cancelTransaction\`) so the queue moved: ${jammed.map((t) => tx(t.hash)).join(" · ")}.`);
out();

const unapplied = seed.txs.filter((t) => ["FINALIZED", "CANCELED", "UNDETERMINED"].includes(t.status) && /(file|judge) #\d/.test(t.label));
out("### Rounds Studio Dev finalized without agreement");
out();
out(`${unapplied.length} filing/judgment rounds came back without an agreed result — FINALIZED while the validators had voted \`timeout\` ("GenVM internal error"), or CANCELED by Studio — and **no state was applied** (docs/PROBE_V2.md §6). The seed read the chain after every write, saw nothing had changed, and sent the call again; the table above links only the rounds whose state is on chain. The first Instagram + Facebook refusal was such a round (leader-only), so it was re-run until two validators agreed and the refusal counter moved: ${unapplied.map((t) => tx(t.hash)).join(" · ")}`);
out();

out("## Snapshots and timelines");
out();
for (const [name, url] of [["WhatsApp (Google Play)", "https://play.google.com/store/apps/details?id=com.whatsapp"],
  ["WhatsApp (App Store)", "https://apps.apple.com/us/app/whatsapp-messenger/id310633997"],
  ["Snapchat (Google Play)", "https://play.google.com/store/apps/details?id=com.snapchat.android"],
  ["LinkedIn (Google Play)", "https://play.google.com/store/apps/details?id=com.linkedin.android"]]) {
  const tl = await view("timeline", [url, 0, 60]);
  tl.items = tl.items.slice().reverse();     // oldest first for the table
  out(`**${name}** — ${tl.total} snapshots (${tl.changes} with a change; filings and judgments are recorded only when the label changed)`);
  out();
  out("| at (UTC) | source | case | hash | changed vs previous | diff (code) |");
  out("|---|---|---|---|---|---|");
  for (const r of tl.items) {
    const d = r.diff ? ["collected", "shared", "none"].map((g) => [...r.diff[g].added.map((x) => `+${g}:${x}`), ...r.diff[g].removed.map((x) => `−${g}:${x}`)]).flat().join(" ") || "none" : "first";
    out(`| ${new Date(r.at * 1000).toISOString().slice(0, 19)} | ${r.source} | ${r.case_id || ""} | \`${r.hash}\` | ${r.changed ? "yes" : "no"} | ${d} |`);
  }
  out();
}
const snapTx = seed.txs.filter((t) => t.method === "snapshot");
out("Snapshot transactions: " + snapTx.map((t) => `${t.label} ${tx(t.hash)}`).join(" · "));
out();

out("## Withdraw flows");
out();
out("| wallet | call | paid | tx |");
out("|---|---|---|---|");
for (const t of seed.txs.filter((t) => t.method === "withdraw" || t.method === "withdraw_fees")) {
  out(`| ${t.label} | \`${t.method}\` | ${t.returned?.status === "OK" ? gen(t.returned.paid_wei) + " GEN" : "refused: " + (t.returned?.reason ?? t.status)} | ${tx(t.hash)} |`);
}
out();

out("## Consumer reads (`AppTrustConsumerV2.app_record`)");
out();
out("| listing | contradicted | verified | corrected | inconclusive | verified developer | last snapshot | trust score |");
out("|---|---|---|---|---|---|---|---|");
for (const [name, url] of [["Snapchat · Play", "https://play.google.com/store/apps/details?id=com.snapchat.android"],
  ["Snapchat · App Store", "https://apps.apple.com/us/app/snapchat/id447188370"],
  ["CapCut · Play", "https://play.google.com/store/apps/details?id=com.lemon.lvoverseas"],
  ["WhatsApp · Play", "https://play.google.com/store/apps/details?id=com.whatsapp"],
  ["LinkedIn · Play", "https://play.google.com/store/apps/details?id=com.linkedin.android"],
  ["Pinterest · Play", "https://play.google.com/store/apps/details?id=com.pinterest"]]) {
  const r = plain(await K.view("app_record", [url]));
  out(`| ${name} | ${r.contradicted} | ${r.verified} | ${r.corrected} | ${r.inconclusive} | ${r.verified_developer} | ${r.last_snapshot_at ? new Date(r.last_snapshot_at * 1000).toISOString().slice(0, 19) : "—"} | ${r.trust_score} |`);
}
out();

const checked = seed.txs.filter((t) => t.ledger);
const broken = checked.filter((t) => !t.ledger.ok);
out("## Ledger identity after every transaction");
out();
out(`After each of the **${checked.length}** seed transactions the script read \`get_stats\` back from the chain: \`balance == locked + claimable + protocol\` held **${checked.length - broken.length} / ${checked.length}** times${broken.length ? " — BROKEN after: " + broken.map((t) => t.label).join(", ") : ""}.`);
out();

const s = await view("get_stats");
out("## The books after the run");
out();
out(`cases ${s.cases} · judgments ${s.judgments} · snapshots ${s.snapshots} · refusals ${s.refusals}`);
out();
out(`balance ${gen(s.balance_wei)} = open stakes ${gen(s.locked_wei)} + claimable ${gen(s.claimable_wei)} + protocol ${gen(s.protocol_wei)} GEN → **${s.ledger_balanced ? "identity holds" : "IDENTITY BROKEN"}**. Withdrawn ${gen(s.total_withdrawn_wei)} GEN; chain balance ${s.chain_balance_wei === "unknown" ? "unknown" : gen(s.chain_balance_wei) + " GEN"} (Studio Dev does not execute value transfers — measured, docs/PROBE_V2.md §5 — so withdrawn GEN is booked out but not delivered: undelivered ${gen(s.undelivered_wei)} GEN).`);
out();
out("## CORRECTED");
out();
out("No CORRECTED verdict could be produced honestly on chain: it needs a real listing to change its label between filing and judgment (10 minutes on the demo), and none did during the run. The path is proven offline with real captured labels edited the way a developer would fix them: `TestJudgeCross.test_threat_label_fixed_between_filing_and_judgment`, `TestJudgePolicy.test_corrected_by_label_edit`, `TestJudgeLabelKind.test_corrected`, and the fixed-then-reverted case `TestJudgeCross.test_threat_label_fixed_then_reverted`.");
out();
out("## Verified developer success path");
out();
out("No real app's website publishes `/.well-known/appaudit.txt`, so only the refusal paths run live (above: file served but wallet absent — Temu, Pinterest; no file — Snapchat). The success path, gating, re-verification and revocation are proven offline: `TestDeveloper.*`.");
writeFileSync(new URL("../docs/SEEDS.md", import.meta.url), lines.join("\n") + "\n");
console.log(`wrote docs/SEEDS.md — ${Object.keys(cases).length} cases, ${mismatches.length} mismatch(es), agreement ${agreeN}/${totalN}`);
