/**
 * Writes docs/EVIDENCE.md and docs/seed-evidence.json by READING THE CHAIN.
 * A seed script's memory is not evidence; what the contract returns is.
 *
 *   node collect.mjs
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { connect } from "./harness.mjs";

const dep = JSON.parse(readFileSync(new URL("../deployments.json", import.meta.url))).deployments.studiodev;
const address = dep.AppAuditDemo.address;
const c = connect({ address, role: "trigger" });
const K = connect({ address: dep.AppTrustConsumer.address, role: "trigger" });
const plain = (v) => JSON.parse(JSON.stringify(v, (k, x) => (typeof x === "bigint" ? x.toString() : x instanceof Map ? Object.fromEntries(x) : x)));
const gen = (w) => (Number(BigInt(w ?? "0")) / 1e18).toString();

const stats = plain(await c.view("get_stats"));
const list = plain(await c.view("get_challenges", [0, 100]));
const rows = [];
for (const card of [...list.items].reverse()) {
  const ch = plain(await c.view("get_challenge", [card.challenge_id]));
  const v = ch.judged_at > 0 ? plain(await c.view("verify_judgment", [card.challenge_id])) : null;
  rows.push({ ch, verified: v ? v.verified : null });
}
const apps = plain(await c.view("get_apps", [0, 50]));
const consumer = {};
for (const url of ["https://play.google.com/store/apps/details?id=com.whatsapp", "https://apps.apple.com/us/app/instagram/id389801252",
  "https://play.google.com/store/apps/details?id=com.spotify.music"]) {
  consumer[url] = {
    is_contradicted: plain(await K.view("is_contradicted", [url])),
    trust: plain(await K.view("get_trust_score", [url])),
  };
}
const listings = plain(await K.view("get_listings"));
const seedLog = existsSync(new URL("../docs/seed-run.log", import.meta.url))
  ? readFileSync(new URL("../docs/seed-run.log", import.meta.url), "utf8") : "";

writeFileSync(new URL("../docs/seed-evidence.json", import.meta.url), JSON.stringify({ address, stats, rows, apps, consumer, listings }, null, 2) + "\n");

let md = `# EVIDENCE — read from the chain\n\nGenerated by \`test/collect.mjs\` at ${new Date().toISOString()} from the **demo instance**\n\`${address}\` on GenLayer Studio Dev (chain 61997). Every value below was returned by a\ncontract view at that moment; nothing was copied from the seed script's own output.\n\n`;
md += `## Challenges\n\n| # | app | claim | status | verdict | case | strength | winner | settlement (adv / dev / protocol GEN) | verify |\n|---|---|---|---|---|---|---|---|---|---|\n`;
for (const { ch, verified } of rows) {
  const s = ch.settlement;
  md += `| ${ch.challenge_id} | \`${ch.app_key}\` | ${ch.claim} | ${ch.status} | ${ch.outcome || "—"}${ch.contest.result ? ` (contest ${ch.contest.result}: ${ch.contest.original_outcome} → ${ch.outcome})` : ""} | ${ch.case || "—"} | ${ch.judged_at ? ch.evidence_strength : "—"} | ${ch.winner} | ${gen(s.owed_advocate_wei)} / ${gen(s.owed_respondent_wei)} / ${gen(s.owed_protocol_wei)} ${s.locked_wei === "0" ? "· paid" : "· **" + gen(s.locked_wei) + " locked**"} | ${verified === null ? "—" : verified ? "✔ recomputes" : "✘"} |\n`;
}
md += `\n## What validators read\n\n`;
for (const { ch } of rows.filter((r) => r.ch.judged_at > 0)) {
  md += `### #${ch.challenge_id} ${ch.app_key} — ${ch.outcome}\n\n- fetched: ${ch.fetch_url}\n- page state \`${ch.page_state}\`, section hash \`${ch.section_hash}\`, content hash \`${ch.content_hash}\`\n- allowed by the bracket: ${ch.allowed.join(", ")}; model called: ${ch.model_called}\n- reason: ${ch.reason}\n\n\`\`\`\n${ch.privacy_text || "(none)"}\n\`\`\`\n\n`;
}
md += `## The books\n\n| field | value |\n|---|---|\n`;
for (const k of ["challenges", "judgments", "contests", "flips", "refusals", "balance_wei", "locked_wei", "refundable_wei", "ledger_balanced", "total_staked_wei", "total_protocol_wei", "total_paid_wei", "chain_balance_wei", "undelivered_wei"]) {
  md += `| \`${k}\` | ${JSON.stringify(stats[k])} |\n`;
}
md += `\n\`balance_wei\` is the contract's own book of what it still owes. When every challenge is terminal and\nclaimed it must read **0**. \`chain_balance_wei\` / \`undelivered_wei\` report Studio Dev's measured habit of\nqueueing \`on="finalized"\` transfers without executing them — a network property reported, not hidden.\n\n`;
md += `## Apps\n\n| app | badge | challenges | contradicted | verified | inconclusive | defaulted |\n|---|---|---|---|---|---|---|\n`;
for (const a of apps.items) md += `| \`${a.app_key}\` | ${a.badge} | ${a.counts.total} | ${a.counts.contradicted} | ${a.counts.verified} | ${a.counts.inconclusive} | ${a.counts.defaulted} |\n`;
md += `\n## Composability — AppTrustConsumer \`${dep.AppTrustConsumer.address}\`\n\n| app | is_contradicted | trust score |\n|---|---|---|\n`;
for (const [url, v] of Object.entries(consumer)) md += `| ${url} | ${v.is_contradicted} | ${v.trust.trust_score} |\n`;
md += `\nRecorded listing decisions:\n\n`;
for (const l of listings.items ?? []) md += `- \`${l.app_key}\` → ${l.listed ? "LISTED" : "REFUSED"} (score ${l.trust_score}): ${l.reason}\n`;
if (seedLog) md += `\n## Seed transcript\n\n\`\`\`\n${seedLog}\`\`\`\n`;
writeFileSync(new URL("../docs/EVIDENCE.md", import.meta.url), md);
console.log("wrote docs/EVIDENCE.md", rows.length, "challenges; balance", stats.balance_wei, "balanced", stats.ledger_balanced);
